# -*- coding: utf-8 -*-
"""01_rdkit_molecular_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0zUT-atYyQXvLq--F0PGff0gCHyhgiy
"""

# Install necessary libraries
!pip install rdkit-pypi rdkit

#Import of required libraries
import pandas as pd

from rdkit import Chem
from rdkit.Chem import Descriptors

#Loading database
df = pd.read_csv('APIs.csv', sep=",")

#Check if data is loadead and what are column names
df.columns

# Calculate and print the total number of missing values
df.isna().sum().sum()

"""# Descriptors"""

from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors

# Assuming your DataFrame is named 'df_percent' and contains the 'API' column with SMILES strings

# Define the functional descriptor calculation
def calculate_descriptors(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol:
            # Use a predefined set of descriptors
            descriptor_calculator = MoleculeDescriptors.MolecularDescriptorCalculator(
                [desc[0] for desc in Descriptors.descList]  # Using all available descriptors
            )
            descriptors = descriptor_calculator.CalcDescriptors(mol)
            return descriptors
        else:
            return [None] * len(Descriptors.descList)  # Return a list of Nones if mol is None
    except Exception as e:
        print(f"Error processing {smiles}: {e}")
        return [None] * len(Descriptors.descList)  # Return Nones if there's an error

# Step 2: Calculate descriptors for each SMILES string
descriptor_values = [calculate_descriptors(smiles) for smiles in df['SMILEs']]
descriptor_names = [desc[0] for desc in Descriptors.descList]  # List of descriptor names
descriptor_data = pd.DataFrame(descriptor_values, columns=descriptor_names)
descriptor_data = descriptor_data.select_dtypes(include=['number'])

numeric_data

# Combine descriptors with df_percent, retaining additional columns
combined_data = pd.concat([df, descriptor_data], axis=1)

# Remove columns with any NA values
cleaned_data = combined_data.dropna(axis=1)

cleaned_data.columns.tolist()

"""# Save data - for future use"""

cleaned_data.to_csv("APIs_descriptors.csv", index=False)

# Install necessary libraries
!pip install rdkit-pypi rdkit

#Import of required libraries
import pandas as pd

from rdkit import Chem
from rdkit.Chem import Descriptors

#Loading database
df = pd.read_csv('APIs.csv', sep=",")

#Check if data is loadead and what are column names
df.columns

# Calculate and print the total number of missing values
df.isna().sum().sum()

from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors

# Assuming your DataFrame is named 'df_percent' and contains the 'API' column with SMILES strings

# Define the functional descriptor calculation
def calculate_descriptors(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol:
            # Use a predefined set of descriptors
            descriptor_calculator = MoleculeDescriptors.MolecularDescriptorCalculator(
                [desc[0] for desc in Descriptors.descList]  # Using all available descriptors
            )
            descriptors = descriptor_calculator.CalcDescriptors(mol)
            return descriptors
        else:
            return [None] * len(Descriptors.descList)  # Return a list of Nones if mol is None
    except Exception as e:
        print(f"Error processing {smiles}: {e}")
        return [None] * len(Descriptors.descList)  # Return Nones if there's an error

# Step 2: Calculate descriptors for each SMILES string
descriptor_values = [calculate_descriptors(smiles) for smiles in df['SMILEs']]
descriptor_names = [desc[0] for desc in Descriptors.descList]  # List of descriptor names
descriptor_data = pd.DataFrame(descriptor_values, columns=descriptor_names)
descriptor_data = descriptor_data.select_dtypes(include=['number'])

# Assuming 'numeric_data' was intended to be 'descriptor_data' based on the output
# display(descriptor_data) # Uncomment if you want to display the descriptor data

# Combine descriptors with df_percent, retaining additional columns
combined_data = pd.concat([df, descriptor_data], axis=1)

# Remove columns with any NA values
cleaned_data = combined_data.dropna(axis=1)

# Display cleaned data columns
# print(cleaned_data.columns.tolist()) # Uncomment if you want to print the columns

# Save data - for future use
cleaned_data.to_csv("APIs_descriptors.csv", index=False)